#! /usr/bin/env ruby

require 'letters'
require 'clipboard'

require_relative './lib/phone_crawler'

class OlxAppError < Exception
end

class OlxApp
  attr_reader :url

  def run
    phones = PhoneCrawler.get_phones(get_url)

    unless phones.empty?
      phones.each do |phone|
        puts " ☎  #{phone}"
      end
      exit
    end

    fail OlxAppError, 'No phones where found!'
  end

  def error(message)
    puts "ERROR: #{message}"
    exit
  end

  private

  def get_url
    url = Clipboard.paste.strip
    @url = url

    fail OlxAppError, 'URL is empty!' if !url || url.empty?

    url
  end
end

app = OlxApp.new

begin
  app.run
rescue OlxAppError => e
  app.error(e.message)
rescue Errno::ECONNREFUSED, URI::InvalidURIError => e
  app.error("Wrong URL was passed! `#{app.url.split(/\R/).join(' ')}`")
rescue SocketError
  app.error('Network error occurred!')
end
